name: Build CI

on:
  workflow_dispatch:
  push:
    branches: [master]
    
jobs:

  test:

    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
                
    steps:
    
    - uses: actions/checkout@v3
    - name: Build
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          docker-compose build
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install colima docker docker-machine docker-compose
          colima start
          docker-compose build
        fi
