name: Build CI

on:
  workflow_dispatch:
  push:
    branches: [master]
    
jobs:

  test:

    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
                
    steps:
    - name: Build
      run: docker-compose build
