name: Build CI

on:
  workflow_dispatch:
  push:
    branches: [master]
    
jobs:

  test:

    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
                
    steps:
    
    - uses: actions/checkout@v3
    - name: Build
      if: matrix.os == ubuntu-latest
      run: |
        docker-compose build
      
    - uses: actions/checkout@v3
    - name: Build
      if: matrix.os == macos-latest
      run: |
        brew install docker docker-machine docker-compose
        docker-compose build
        
