name: Build CI

on:
  workflow_dispatch:
  push:
    branches: [master]
    
jobs:

  test:

    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
                
    steps:
    
    - uses: actions/checkout@v3
    - name: Build
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          docker-compose build
          timeout 1m docker-compose up || [ $? -eq 124 ]
        elif [ "$RUNNER_OS" == "Windows" ]; then
          C:\Program Files\Docker\Docker\DockerCli.exe -SwitchLinuxEngine
          docker-compose build
          timeout 1m docker-compose up || [ $? -eq 124 ]
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install coreutils colima docker docker-machine docker-compose
          colima start
          docker-compose build
          gtimeout 1m docker-compose up || [ $? -eq 124 ]
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi
