name: Build CI

on:
  workflow_dispatch:
  push:
    branches: [master]
    
jobs:

  test:

    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
                
    steps:
    
    - uses: actions/checkout@v3
    - name: Build
      if: startsWith(runner.os, 'Linux')
      run: |
        docker-compose build

    - uses: actions/checkout@v3
    - name: Build
      if: startsWith(runner.os, 'Windows')
      run: |
        "C:\Program Files\Docker\Docker\DockerCli.exe -SwitchDaemon"
        docker-compose build
        
    - uses: actions/checkout@v3
    - name: Build
      if: startsWith(runner.os, 'macOS')
      run: |
        brew install colima docker docker-machine docker-compose
        colima start
        docker-compose build
